---
image:
  tag: 1.2.1-alpine
extraVars:
  - name: CMD_DOMAIN
    value: {{ hackmd.domain }}
  - name: CMD_PROTOCOL_USESSL
    value: "true"
  - name: CMD_URL_ADDPORT
    value: "false"
  - name: CMD_ALLOW_FREEURL
    value: "true"
  - name: CMD_ALLOW_ANONYMOUS
    value: "true"
  - name: CMD_GITHUB_CLIENTID
    value: "{{ hackmd.github.client_id }}"
  - name: CMD_GITHUB_CLIENTSECRET
    value: "{{ hackmd.github.secret }}"
  - name: CMD_EMAIL
    value: "false"
  - name: CMD_ALLOW_EMAIL_REGISTER
    value: "false"
  - name: CMD_IMAGE_UPLOAD_TYPE
    value: "filesystem"

ingress:
  enabled: true
  hosts:
    - {{ hackmd.domain }}
{%- if ingress.tls %}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  tls:
    - secretName: hackmd-tls
      hosts:
        - {{ hackmd.domain }}
{%- endif %}

postgresql:
  postgresPassword: "{{ hackmd.postgresql.postgresPassword }}"
  persistence:
    existingClaim: "{{ hackmd.postgresql.existingClaim }}"

persistence:
  existingClaim: "{{ hackmd.existingClaim }}"
