---
# The nodes that are going to mount the erasure coded RBD block storage must have Linux kernel >= `4.11`.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-block
provisioner: ceph.rook.io/block
parameters:
  # If you want to use erasure coded pool with RBD, you need to create two pools (as seen above): one erasure coded and one replicated.
  # You need to specify the replicated pool here in the `pool` parameter, it is used for the metadata of the images.
  # The erasure coded pool must be set as the `dataPool` parameter below.
  pool: replicated-pool
  # pool: ec-data-pool
  # dataPool: ec-data-pool
  # Specify the namespace of the rook cluster from which to create volumes.
  # If not specified, it will use `rook` as the default namespace of the cluster.
  # This is also the namespace where the cluster will be
  clusterNamespace: rook-ceph
  # Specify the filesystem type of the volume. If not specified, it will use `ext4`.
  fstype: xfs
