---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
  labels:
    use: "owncloud"
  name: "owncloud"
  namespace: "owncloud"
spec:
  storageClassName: "slow"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "10Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
  labels:
    use: "owncloud-apache"
  name: "owncloud-apache"
  namespace: "owncloud"
spec:
  storageClassName: "slow"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "10Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    use: "owncloud-mariadb"
  name: "owncloud-mariadb"
  namespace: "owncloud"
spec:
  storageClassName: "rook-ceph-block"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "10Gi"
