#!/usr/bin/env bash
set -eu
export LC_ALL=C

cat <<EOF
#cloud-config
---
hostname: ${NODE_HOSTNAME}

# Set SSH Key
ssh_authorized_keys:
- ${NODE_PUBLIC_KEY}

network:
  config: disabled

runcmd:
  - [ sh, -c, "echo '${NODE_ADDRESS}  ${NODE_HOSTNAME}' >> /etc/hosts"]
EOF
