#!/usr/bin/env bash
set -eu
export LC_ALL=C

cat <<EOF
#cloud-config
---
hostname: ${NODE_HOSTNAME}
# password: password
# chpasswd: {expire: False}

# Set SSH Key
ssh_authorized_keys:
- ${NODE_PUBLIC_KEY}

network:
  config: disabled

runcmd:
  - [ sh, -c, "echo '${NODE_ADDRESS}  ${NODE_HOSTNAME}' >> /etc/hosts"]
  - [ sh, -c, "curl https://github.com/${NODE_GITHUB_USER}.keys >> /home/ubuntu/.ssh/authorized_keys" ]

apt:
  sources:
    docker:
      keyid: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
      keyserver: "keyserver.ubuntu.com"
      source: "deb [arch=amd64] https://download.docker.com/linux/ubuntu ${NODE_OS_CODENAME} stable"

packages:
- docker-ce
- docker-ce-cli
- containerd.io
- conntrack

EOF
